package widget;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table WIDGET_ID.
 */
public class WidgetID {

    private Long id;
    private int tvID;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public WidgetID() {
    }

    public WidgetID(int tvID) {
        this.tvID = tvID;
    }

    public WidgetID(Long id) {
        this.id = id;
    }

    public WidgetID(Long id, int tvID) {
        this.id = id;
        this.tvID = tvID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getTvID() {
        return tvID;
    }

    public void setTvID(int tvID) {
        this.tvID = tvID;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
