package timedao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import timedao.MyTime;

import timedao.MyTimeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig myTimeDaoConfig;

    private final MyTimeDao myTimeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        myTimeDaoConfig = daoConfigMap.get(MyTimeDao.class).clone();
        myTimeDaoConfig.initIdentityScope(type);

        myTimeDao = new MyTimeDao(myTimeDaoConfig, this);

        registerDao(MyTime.class, myTimeDao);
    }
    
    public void clear() {
        myTimeDaoConfig.getIdentityScope().clear();
    }

    public MyTimeDao getMyTimeDao() {
        return myTimeDao;
    }

}
