package timedao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import timedao.MyTime;
import timedao.WidgetID;

import timedao.MyTimeDao;
import timedao.WidgetIDDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig myTimeDaoConfig;
    private final DaoConfig widgetIDDaoConfig;

    private final MyTimeDao myTimeDao;
    private final WidgetIDDao widgetIDDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        myTimeDaoConfig = daoConfigMap.get(MyTimeDao.class).clone();
        myTimeDaoConfig.initIdentityScope(type);

        widgetIDDaoConfig = daoConfigMap.get(WidgetIDDao.class).clone();
        widgetIDDaoConfig.initIdentityScope(type);

        myTimeDao = new MyTimeDao(myTimeDaoConfig, this);
        widgetIDDao = new WidgetIDDao(widgetIDDaoConfig, this);

        registerDao(MyTime.class, myTimeDao);
        registerDao(WidgetID.class, widgetIDDao);
    }
    
    public void clear() {
        myTimeDaoConfig.getIdentityScope().clear();
        widgetIDDaoConfig.getIdentityScope().clear();
    }

    public MyTimeDao getMyTimeDao() {
        return myTimeDao;
    }

    public WidgetIDDao getWidgetIDDao() {
        return widgetIDDao;
    }

}
