package timedao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import timedao.MyTime;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table MY_TIME.
*/
public class MyTimeDao extends AbstractDao<MyTime, Long> {

    public static final String TABLENAME = "MY_TIME";

    /**
     * Properties of entity MyTime.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Timecode = new Property(1, String.class, "timecode", false, "TIMECODE");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Year = new Property(3, Integer.class, "year", false, "YEAR");
        public final static Property Monthofyear = new Property(4, Integer.class, "monthofyear", false, "MONTHOFYEAR");
        public final static Property Dayofmonth = new Property(5, Integer.class, "dayofmonth", false, "DAYOFMONTH");
        public final static Property Dayofweek = new Property(6, Integer.class, "dayofweek", false, "DAYOFWEEK");
        public final static Property Starthour = new Property(7, Integer.class, "starthour", false, "STARTHOUR");
        public final static Property Startmin = new Property(8, Integer.class, "startmin", false, "STARTMIN");
        public final static Property Endhour = new Property(9, Integer.class, "endhour", false, "ENDHOUR");
        public final static Property Endmin = new Property(10, Integer.class, "endmin", false, "ENDMIN");
        public final static Property Startmillis = new Property(11, Integer.class, "startmillis", false, "STARTMILLIS");
        public final static Property Endmillis = new Property(12, Integer.class, "endmillis", false, "ENDMILLIS");
        public final static Property Memo = new Property(13, String.class, "memo", false, "MEMO");
        public final static Property Place = new Property(14, String.class, "place", false, "PLACE");
        public final static Property Lat = new Property(15, Double.class, "lat", false, "LAT");
        public final static Property Lng = new Property(16, Double.class, "lng", false, "LNG");
        public final static Property Share = new Property(17, Integer.class, "share", false, "SHARE");
        public final static Property Alarm = new Property(18, String.class, "alarm", false, "ALARM");
        public final static Property Repeat = new Property(19, String.class, "repeat", false, "REPEAT");
        public final static Property Color = new Property(20, String.class, "color", false, "COLOR");
    };


    public MyTimeDao(DaoConfig config) {
        super(config);
    }
    
    public MyTimeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'MY_TIME' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'TIMECODE' TEXT," + // 1: timecode
                "'NAME' TEXT," + // 2: name
                "'YEAR' INTEGER," + // 3: year
                "'MONTHOFYEAR' INTEGER," + // 4: monthofyear
                "'DAYOFMONTH' INTEGER," + // 5: dayofmonth
                "'DAYOFWEEK' INTEGER," + // 6: dayofweek
                "'STARTHOUR' INTEGER," + // 7: starthour
                "'STARTMIN' INTEGER," + // 8: startmin
                "'ENDHOUR' INTEGER," + // 9: endhour
                "'ENDMIN' INTEGER," + // 10: endmin
                "'STARTMILLIS' INTEGER," + // 11: startmillis
                "'ENDMILLIS' INTEGER," + // 12: endmillis
                "'MEMO' TEXT," + // 13: memo
                "'PLACE' TEXT," + // 14: place
                "'LAT' REAL," + // 15: lat
                "'LNG' REAL," + // 16: lng
                "'SHARE' INTEGER," + // 17: share
                "'ALARM' TEXT," + // 18: alarm
                "'REPEAT' TEXT," + // 19: repeat
                "'COLOR' TEXT);"); // 20: color
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'MY_TIME'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, MyTime entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String timecode = entity.getTimecode();
        if (timecode != null) {
            stmt.bindString(2, timecode);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        Integer year = entity.getYear();
        if (year != null) {
            stmt.bindLong(4, year);
        }
 
        Integer monthofyear = entity.getMonthofyear();
        if (monthofyear != null) {
            stmt.bindLong(5, monthofyear);
        }
 
        Integer dayofmonth = entity.getDayofmonth();
        if (dayofmonth != null) {
            stmt.bindLong(6, dayofmonth);
        }
 
        Integer dayofweek = entity.getDayofweek();
        if (dayofweek != null) {
            stmt.bindLong(7, dayofweek);
        }
 
        Integer starthour = entity.getStarthour();
        if (starthour != null) {
            stmt.bindLong(8, starthour);
        }
 
        Integer startmin = entity.getStartmin();
        if (startmin != null) {
            stmt.bindLong(9, startmin);
        }
 
        Integer endhour = entity.getEndhour();
        if (endhour != null) {
            stmt.bindLong(10, endhour);
        }
 
        Integer endmin = entity.getEndmin();
        if (endmin != null) {
            stmt.bindLong(11, endmin);
        }
 
        Integer startmillis = entity.getStartmillis();
        if (startmillis != null) {
            stmt.bindLong(12, startmillis);
        }
 
        Integer endmillis = entity.getEndmillis();
        if (endmillis != null) {
            stmt.bindLong(13, endmillis);
        }
 
        String memo = entity.getMemo();
        if (memo != null) {
            stmt.bindString(14, memo);
        }
 
        String place = entity.getPlace();
        if (place != null) {
            stmt.bindString(15, place);
        }
 
        Double lat = entity.getLat();
        if (lat != null) {
            stmt.bindDouble(16, lat);
        }
 
        Double lng = entity.getLng();
        if (lng != null) {
            stmt.bindDouble(17, lng);
        }
 
        Integer share = entity.getShare();
        if (share != null) {
            stmt.bindLong(18, share);
        }
 
        String alarm = entity.getAlarm();
        if (alarm != null) {
            stmt.bindString(19, alarm);
        }
 
        String repeat = entity.getRepeat();
        if (repeat != null) {
            stmt.bindString(20, repeat);
        }
 
        String color = entity.getColor();
        if (color != null) {
            stmt.bindString(21, color);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public MyTime readEntity(Cursor cursor, int offset) {
        MyTime entity = new MyTime( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // timecode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // year
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // monthofyear
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // dayofmonth
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // dayofweek
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // starthour
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8), // startmin
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9), // endhour
            cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10), // endmin
            cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11), // startmillis
            cursor.isNull(offset + 12) ? null : cursor.getInt(offset + 12), // endmillis
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // memo
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // place
            cursor.isNull(offset + 15) ? null : cursor.getDouble(offset + 15), // lat
            cursor.isNull(offset + 16) ? null : cursor.getDouble(offset + 16), // lng
            cursor.isNull(offset + 17) ? null : cursor.getInt(offset + 17), // share
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // alarm
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // repeat
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20) // color
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, MyTime entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTimecode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setYear(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setMonthofyear(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setDayofmonth(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setDayofweek(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setStarthour(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setStartmin(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
        entity.setEndhour(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
        entity.setEndmin(cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10));
        entity.setStartmillis(cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11));
        entity.setEndmillis(cursor.isNull(offset + 12) ? null : cursor.getInt(offset + 12));
        entity.setMemo(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setPlace(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setLat(cursor.isNull(offset + 15) ? null : cursor.getDouble(offset + 15));
        entity.setLng(cursor.isNull(offset + 16) ? null : cursor.getDouble(offset + 16));
        entity.setShare(cursor.isNull(offset + 17) ? null : cursor.getInt(offset + 17));
        entity.setAlarm(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setRepeat(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setColor(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(MyTime entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(MyTime entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
