package timedao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MY_TIME.
 */
public class MyTime {

    private Long id;
    private String timecode;
    private String name;
    private Integer year;
    private Integer monthofyear;
    private Integer dayofmonth;
    private Integer dayofweek;
    private Integer starthour;
    private Integer startmin;
    private Integer endhour;
    private Integer endmin;
    private Integer startmillis;
    private Integer endmillis;
    private String memo;
    private String place;
    private Double lat;
    private Double lng;
    private Integer share;
    private String alarm;
    private String repeat;
    private String color;

    public MyTime() {
    }

    public MyTime(Long id) {
        this.id = id;
    }

    public MyTime(Long id, String timecode, String name, Integer year, Integer monthofyear, Integer dayofmonth, Integer dayofweek, Integer starthour, Integer startmin, Integer endhour, Integer endmin, Integer startmillis, Integer endmillis, String memo, String place, Double lat, Double lng, Integer share, String alarm, String repeat, String color) {
        this.id = id;
        this.timecode = timecode;
        this.name = name;
        this.year = year;
        this.monthofyear = monthofyear;
        this.dayofmonth = dayofmonth;
        this.dayofweek = dayofweek;
        this.starthour = starthour;
        this.startmin = startmin;
        this.endhour = endhour;
        this.endmin = endmin;
        this.startmillis = startmillis;
        this.endmillis = endmillis;
        this.memo = memo;
        this.place = place;
        this.lat = lat;
        this.lng = lng;
        this.share = share;
        this.alarm = alarm;
        this.repeat = repeat;
        this.color = color;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTimecode() {
        return timecode;
    }

    public void setTimecode(String timecode) {
        this.timecode = timecode;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getYear() {
        return year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }

    public Integer getMonthofyear() {
        return monthofyear;
    }

    public void setMonthofyear(Integer monthofyear) {
        this.monthofyear = monthofyear;
    }

    public Integer getDayofmonth() {
        return dayofmonth;
    }

    public void setDayofmonth(Integer dayofmonth) {
        this.dayofmonth = dayofmonth;
    }

    public Integer getDayofweek() {
        return dayofweek;
    }

    public void setDayofweek(Integer dayofweek) {
        this.dayofweek = dayofweek;
    }

    public Integer getStarthour() {
        return starthour;
    }

    public void setStarthour(Integer starthour) {
        this.starthour = starthour;
    }

    public Integer getStartmin() {
        return startmin;
    }

    public void setStartmin(Integer startmin) {
        this.startmin = startmin;
    }

    public Integer getEndhour() {
        return endhour;
    }

    public void setEndhour(Integer endhour) {
        this.endhour = endhour;
    }

    public Integer getEndmin() {
        return endmin;
    }

    public void setEndmin(Integer endmin) {
        this.endmin = endmin;
    }

    public Integer getStartmillis() {
        return startmillis;
    }

    public void setStartmillis(Integer startmillis) {
        this.startmillis = startmillis;
    }

    public Integer getEndmillis() {
        return endmillis;
    }

    public void setEndmillis(Integer endmillis) {
        this.endmillis = endmillis;
    }

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public String getPlace() {
        return place;
    }

    public void setPlace(String place) {
        this.place = place;
    }

    public Double getLat() {
        return lat;
    }

    public void setLat(Double lat) {
        this.lat = lat;
    }

    public Double getLng() {
        return lng;
    }

    public void setLng(Double lng) {
        this.lng = lng;
    }

    public Integer getShare() {
        return share;
    }

    public void setShare(Integer share) {
        this.share = share;
    }

    public String getAlarm() {
        return alarm;
    }

    public void setAlarm(String alarm) {
        this.alarm = alarm;
    }

    public String getRepeat() {
        return repeat;
    }

    public void setRepeat(String repeat) {
        this.repeat = repeat;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

}
