package timedao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table WIDGET_ID.
 */
public class WidgetID {

    private Long id;
    private int tvID;

    public WidgetID() {
    }

    public WidgetID(int tvID) {
        this.tvID = tvID;
    }

    public WidgetID(Long id) {
        this.id = id;
    }

    public WidgetID(Long id, int tvID) {
        this.id = id;
        this.tvID = tvID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getTvID() {
        return tvID;
    }

    public void setTvID(int tvID) {
        this.tvID = tvID;
    }

}
